package com.webcapsule.reactnative.runtime

enum class WebCapsuleErrorCode {
  INVALID_ARGUMENT, INVALID_JSON_VALUE, DUPLICATE_JSON_KEY, INVALID_MANIFEST, INVALID_TIMESTAMP,
  INVALID_POLICY, INVALID_SIGNATURE, INVALID_ORDER, UNSUPPORTED_FORMAT_VERSION,
  INVALID_CAPSULE_ID, INVALID_KEY_ID, INVALID_VERSION, INVALID_HASH,
  INVALID_MEDIA_TYPE, INVALID_PATH, DUPLICATE_PATH, CASE_COLLISION,
  UNICODE_COLLISION, LIMIT_EXCEEDED, ARCHIVE_INVALID, INVALID_ARCHIVE_PROFILE,
  SIGNATURE_MISMATCH, HASH_MISMATCH, ID_MISMATCH, KEY_ID_MISMATCH,
  RUNTIME_INCOMPATIBLE, INVALID_PUBLIC_KEY, STORAGE_IO_FAILED,
  ATOMIC_PUBLISH_UNSUPPORTED, STORAGE_INVARIANT_VIOLATION, UNSAFE_STORAGE_LAYOUT,
  REGISTRY_INVALID, REGISTRY_RECOVERY_FAILED, VERSION_RECORD_INVALID,
  BLOB_MISSING, INSTALL_FAILED, LOCK_FAILED, BUNDLED_SOURCE_INVALID,
  BUNDLED_CAPSULE_UNAVAILABLE, NO_RUNNABLE_VERSION, SESSION_MISMATCH,
  RESOURCE_DENIED, ENTRY_LOAD_FAILED, READY_MESSAGE_INVALID, READY_TIMEOUT, STABILIZATION_FAILED
}

class WebCapsuleException(
  val code: WebCapsuleErrorCode,
  message: String,
  cause: Throwable? = null,
) : Exception(message, cause)

internal fun fail(code: WebCapsuleErrorCode, message: String, cause: Throwable? = null): Nothing =
  throw WebCapsuleException(code, message, cause)
